name: pipeline

on:
  push:
    branches:
      - '*'  
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2

      - name: Install dependencies
        run:  go install

      - name: Build
        run: go build .

      - name: Run testing
        run: go test ./... -v -cover