name: pipeline

on:
  push:
    branches:
      - '*'  
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2

      - name: Install dependencies
        run:  go install

      - name: Build
        run: go build .

      - name: Test
        run: go test ./... -v -cover -coverprofile=coverage.out

      - name: Sonar
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}